server:
  port: 8006
spring:
  application:
    name: consul-provider-payment
  cloud:
    consul:
      host: 192.168.10.128
      port: 8500
    discovery:
      service-name: ${spring.application.name}
